### ISSUE TITLE
knnmi.all

### ISSUE THREAD

**Issue by handesome** [sales-lab/parmigene#3]
Hi!
when I use knnmi.all to get the gene matrix's MI,there are some negatives in the result.But MI should be always positive. Could anyone explain the reason?

**Comment by gbrsales** [comment]
Hi,

**Comment by gbrsales** [comment]
Hi,
 
the mutual information provided by the `knnmi.all()` is an estimate, not an exact value. This estimate is subject to numerical limitations and can sometimes result in slightly negative values. You can consider these values as effectively 0, or round them to 0 if necessary, as they are likely due to numerical noise rather than a meaningful result.
